### ISSUE TITLE
Bug or feature? - Fundo altera cor ao apertar enter

### ISSUE THREAD

**Issue by lucianowayand** [ColmeiaUDESC/site-colmeia#82]
# Ao apertar "Enter" a opacidade vai aumentando

1. ![image](https://user-images.githubusercontent.com/36968613/125460296-d9f6b79a-ec7b-45c1-8867-292a6469c1d1.png)
2. ![image](https://user-images.githubusercontent.com/36968613/125460376-7e121f0d-843c-4428-ae30-3534ec084af2.png)
3. ![image](https://user-images.githubusercontent.com/36968613/125460439-7bc916b9-dd0d-400e-a730-e7e07f5ee0c5.png)
4. ![image](https://user-images.githubusercontent.com/36968613/125460497-593f693c-0a09-4368-98e0-bde56ab8daf3.png)

**Comment by joaodematte** [comment]
provavelmente quando vc clicou pra deletar o comentário, o modal abriu na sua tela, mas o elemento que ainda ta selecionado é o "X" que seria para deletar o comentário, assim, ele vai abrindo infinitos modais na tela.
acho que só resetar o innerHTML da div que o modal é inserido pode ser uma solução.
